spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news_db
  ##url: jdbc:postgresql://db:5432/news_db
    username: postgres_user
    password: postgres_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

app:
  main:
    page: https://mid.ru/ru/foreign_policy/news/

  scraper:
    incognito: true  # ???? ????????? ?????? ?????????

    div:
      page-content: "page-content"
      announce-item: "announce__item"

    random-delay:
      min: 2000    # ??????????? ???????? ? ?????????????
      max: 5000   # ???????????? ???????? ? ?????????????

    cron:
      evening: "0 31 21 * * ?"  # ????????? ?????? ???? ? 20:35
      hourly: "0 0 * * * ?"     # ????????? ?????? ???
      daily: "0 0 9 * * ?"      # ????????? ?????? ???? ? 9:00
